# -*- coding: utf-8 -*-
"""YTTrendVideosAnalysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_EybYsPioinodYaMyvb7VMU27JyOp5f
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import seaborn as sns

import warnings
from collections import Counter
import datetime
import wordcloud
import json

df = pd.read_csv("USvideos.csv")

df.head()

"""Data Exploration"""

df.isnull().sum()
pd.options.display.float_format = '{:.2f}'.format

#lets fill description values
df.description=df.description.fillna("")

df.describe()

"""Data Visualization"""

#lets analyze the title if it consists of at least one upper character
def contains(title):
  for ch in title:
    if ch.isupper():
      return True
    else:
      return False
df.containtUpp=df.title.apply(contains)

value_counts=df.containtUpp.value_counts().to_dict()
value_counts

labels=list(value_counts.keys())
nums=list(value_counts.values())
nums

plt.pie(nums,labels=labels,autopct="%1.1f%%")
plt.title("does title contain uppercse character")

#lets analyze title length
df.titlelen=df.title.apply(len)

sns.distplot(df.titlelen, bins=30, kde=True, color='skyblue')

#lets see relation between views and title length
fig=plt.figure(figsize=(3,3))
ax=fig.add_axes([0,0,1,1])
ax.scatter(df.views,df.titlelen)
fig.show()

#lets see corroleation
corroleated=df.corr(numeric_only=True)
sns.heatmap(corroleated,annot=True,cmap="Blues")

#it indicates that views and likes are strongly positively correlated.

#lets see the most common word
title_words=list(df.title.apply(lambda x:x.split()))
title_words = [x for y in title_words for x in y] #that flattens the nested list

wc = wordcloud.WordCloud(width=1200, height=500,
                         collocations=False, background_color="white",
                         colormap="tab20b").generate(" ".join(title_words))
plt.figure(figsize=(15,10))
plt.imshow(wc, interpolation='bilinear')

